<a href = "https://www.pieriantraining.com"><img src="../PT Centered Purple.png"> </a>

<em style="text-align:center">Copyrighted by Pierian Training</em>

# Tabular Data:  Classification

In this lecture, you are going to build a classifier to predict whether a hotel reservation is canceled or not.
The dataset is based on : https://www.kaggle.com/datasets/ahsan81/hotel-reservations-classification-dataset and has features such as 
- Number of adults
- Room Type
- Avg. Room Price
- Meal Plan
- Car Parking

Our target label for prediction will be checking to see if the reservation was cancelled or not.

### Imports

In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor

At first we use **TabularDataset** to which we either pass the path to the csv data or a pandas dataframe.

### Dataset

TabularDatset can read in tabular data from a CSV or Parquet file. For other data sources, you may want to consider opening with Pandas first, then using TabularDataset after cleaning, reformatting, and saving to another extension like CSV.

In [2]:
data = TabularDataset("data/reservation/Hotel Reservations.csv")

In [3]:
data.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

The resulting dataframe is a standard pandas dataframe

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36275 entries, 0 to 36274
Data columns (total 19 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Booking_ID                            36275 non-null  object
 1   no_of_adults                          36275 non-null  int64
 2   no_of_children                        36275 non-null  int64
 3   no_of_weekend_nights                  36275 non-null  int64
 4   no_of_week_nights                     36275 non-null  int64
 5   type_of_meal_plan                     36275 non-null  object
 6   required_car_parking_space            36275 non-null  int64
 7   room_type_reserved                    36275 non-null  object
 8   lead_time                             36275 non-null  int64
 9   arrival_year                          36275 non-null  int64
 10  arrival_month                         36275 non-null  int64
 11  arrival_date                          36275 non-null  int64
 12  market_segment_type                   36275 non-null  object
 13  repeated_guest                        36275 non-null  int64
 14  no_of_previous_cancellations          36275 non-null  int64
 15  no_of_previous_bookings_not_canceled  36275 non-null  int64
 16  avg_price_per_room                    36275 non-null  float64
 17  no_of_special_requests                36275 non-null  int64
 18  booking_status                        36275 non-null  object
dtypes: float64(1), int64(13), object(5)
memory usage: 5.3+ MB

## Train Test Split

To validate our model, we should create a train-test split.
Let's use 30,000 samples for training and 6275 for testing. To enable deterministic behavior, we define a random seed, that way we can repeat the exact same split in the future.

While you could use Scikit-Learn for this, we can also just take a random sample for our training set, and then drop those rows for our test set.

In [5]:
len(data)

36275

In [6]:
# Optionaly, use a percentage, something like:
# train_size = 0.7*len(data)

In [7]:
train_size = 30000
seed = 42

In [8]:
train_data = data.sample(train_size, random_state=seed)
test_data = data.drop(train_data.index)

In [9]:
train_data.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
4968,INN04969,2,1,1,0,Meal Plan 1,0,Room_Type 1,3,2017,8,23,Online,0,0,0,90.00,3,Not_Canceled
34540,INN34541,2,0,1,2,Meal Plan 1,0,Room_Type 4,9,2018,2,12,Offline,0,0,0,48.67,0,Not_Canceled
36108,INN36109,2,0,2,2,Meal Plan 1,0,Room_Type 1,24,2018,12,25,Online,0,0,0,95.20,1,Not_Canceled
1553,INN01554,2,0,0,3,Meal Plan 1,0,Room_Type 1,23,2018,6,21,Online,0,0,0,127.67,0,Canceled
24974,INN24975,2,1,0,2,Meal Plan 1,0,Room_Type 4,9,2018,9,8,Online,0,0,0,201.50,2,Not_Canceled

In [10]:
test_data.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
9,INN00010,2,0,0,5,Meal Plan 1,0,Room_Type 4,44,2018,10,18,Online,0,0,0,133.44,3,Not_Canceled
16,INN00017,1,0,1,0,Meal Plan 1,0,Room_Type 1,0,2017,10,5,Offline,0,0,0,96.00,0,Not_Canceled
53,INN00054,2,0,0,4,Meal Plan 1,0,Room_Type 4,51,2017,11,11,Offline,0,0,0,60.00,1,Not_Canceled
55,INN00056,2,0,1,3,Meal Plan 1,0,Room_Type 1,100,2018,5,19,Online,0,0,0,136.00,1,Not_Canceled
60,INN00061,2,2,0,1,Meal Plan 1,1,Room_Type 6,2,2018,9,2,Online,0,0,0,258.00,1,Not_Canceled

Note that there are strings in the dataset (like *Offline* or *Not_Canceled*) which we usually need to manually convert to numerical categories. Autogluon performs this task for us! And as you go through this course, you'll discover it can do a lot of work for us!

### Training
To start the training process we use the **TabularPredictor** class to which we pass the label column, *booking_status*, as well as the path where we want to store the models.

In [11]:
save_path = 'reservation_predictors'

Note, you may get a warning if you are overwriting a previous saved file (which is a nice warning to have, we'll ignore it!)

In [12]:
predictor = TabularPredictor(label="booking_status", path=save_path)

Using the **fit()** function, we can start the training.
All you need to do is to pass the training dataset. AutGluon does the rest. Keep in mind, this may take awhie on certain machines, and you should expect a very large amount of text output informing you of the process, including warnings if certain models could not be fitted.

Expect this to run awhile:

In [13]:
predictor.fit(train_data)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.77 GB / 32.00 GB (21.2%)
Disk Space Avail:   121.35 GB / 926.35 GB (13.1%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/reservation_predictors"
Train Data Rows:    30000
Train Data Columns: 18
Label Column:       booking_status
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  ['Not_Canceled', 'Canceled']
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = Not_Canceled, class 0 = Canceled
	Note: For your binary classification, AutoGluon arbitrarily selected which label-value represents positive (Not_Canceled) vs negative (Canceled) class.
	To explicitly set the positive_class, either rename classes to 1 and 0, or specify positive_class in Predictor init.
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6622.89 MB
	Train Data (Original)  Memory Usage: 10.78 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Booking_ID']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Booking_ID']
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  :  1 | ['avg_price_per_room']
		('int', [])    : 13 | ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'required_car_parking_space', ...]
		('object', []) :  3 | ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  :  3 | ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']
		('float', [])     :  1 | ['avg_price_per_room']
		('int', [])       : 10 | ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'lead_time', ...]
		('int', ['bool']) :  3 | ['required_car_parking_space', 'arrival_year', 'repeated_guest']
	0.2s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 2.69 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0833, Train Rows: 27501, Val Rows: 2499
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=10, gpus=0, mem=0.0/6.4 GB
	0.8976	 = Validation score   (accuracy)
	18.15s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=10, gpus=0, mem=0.0/6.6 GB
	0.9064	 = Validation score   (accuracy)
	8.48s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: RandomForestGini ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.4 GB
	0.9132	 = Validation score   (accuracy)
	3.16s	 = Training   runtime
	0.12s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.3 GB
	0.9132	 = Validation score   (accuracy)
	5.09s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=10, gpus=0
	0.8976	 = Validation score   (accuracy)
	12.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB
	0.906	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.3 GB
	0.9088	 = Validation score   (accuracy)
	0.9s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=10, gpus=0, mem=0.0/6.0 GB
	0.8932	 = Validation score   (accuracy)
	32.44s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=10, gpus=0
	0.9044	 = Validation score   (accuracy)
	4.24s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.0/6.5 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	0.8972	 = Validation score   (accuracy)
	82.68s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB
	0.9116	 = Validation score   (accuracy)
	24.03s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/6.6 GB
	Ensemble Weights: {'RandomForestGini': 0.308, 'LightGBMLarge': 0.308, 'ExtraTreesGini': 0.231, 'RandomForestEntr': 0.154}
	0.918	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 195.63s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 7819.9 rows/s (2499 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (2499 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/reservation_predictors")

## Summary of Model Fits

Calling **fit_summary()** creates a beautiful overview over the whole training process, as well as creating an html file that visualizes the different results.
You can see that the *WeightedEnsemble_L2* model achieved the best validation score

In [16]:
predictor.fit_summary(show_plot=True)

*** Summary of fit() ***
Estimated performance of each model:
                  model  score_val eval_metric  pred_time_val   fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0   WeightedEnsemble_L2   0.917967    accuracy       0.319571  33.430055                0.000533           0.058673            2       True         12
1      RandomForestEntr   0.913165    accuracy       0.100036   5.085143                0.100036           5.085143            1       True          4
2      RandomForestGini   0.913165    accuracy       0.122748   3.161451                0.122748           3.161451            1       True          3
3         LightGBMLarge   0.911565    accuracy       0.044688  24.028977                0.044688          24.028977            1       True         11
4        ExtraTreesEntr   0.908764    accuracy       0.046260   0.898610                0.046260           0.898610            1       True          7
5              LightGBM   0.906363    accuracy       0.131173   8.476638                0.131173           8.476638            1       True          2
6        ExtraTreesGini   0.905962    accuracy       0.051566   1.095811                0.051566           1.095811            1       True          6
7               XGBoost   0.904362    accuracy       0.036969   4.243118                0.036969           4.243118            1       True          9
8              CatBoost   0.897559    accuracy       0.013782  12.856600                0.013782          12.856600            1       True          5
9            LightGBMXT   0.897559    accuracy       0.073047  18.154786                0.073047          18.154786            1       True          1
10       NeuralNetTorch   0.897159    accuracy       0.031718  82.684422                0.031718          82.684422            1       True         10
11      NeuralNetFastAI   0.893157    accuracy       0.095311  32.441805                0.095311          32.441805            1       True          8
Number of models trained: 12
Types of models trained:
{'LGBModel', 'CatBoostModel', 'WeightedEnsembleModel', 'XTModel', 'NNFastAiTabularModel', 'XGBoostModel', 'RFModel', 'TabularNeuralNetTorchModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('category', [])  :  3 | ['type_of_meal_plan', 'room_type_reserved', 'market_segment_type']
('float', [])     :  1 | ['avg_price_per_room']
('int', [])       : 10 | ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'lead_time', ...]
('int', ['bool']) :  3 | ['required_car_parking_space', 'arrival_year', 'repeated_guest']
Plot summary of models saved to file: /Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/reservation_predictors/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestGini': 'RFModel',
  'RandomForestEntr': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesGini': 'XTModel',
  'ExtraTreesEntr': 'XTModel',
  'NeuralNetFastAI': 'NNFastAiTabularModel',
  'XGBoost': 'XGBoostModel',
  'NeuralNetTorch': 'TabularNeuralNetTorchModel',
  'LightGBMLarge': 'LGBModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'LightGBMXT': 0.8975590236094437,
  'LightGBM': 0.9063625450180072,
  'RandomForestGini': 0.9131652661064426,
  'RandomForestEntr': 0.9131652661064426,
  'CatBoost': 0.8975590236094437,
  'ExtraTreesGini': 0.9059623849539816,
  'ExtraTreesEntr': 0.9087635054021609,
  'NeuralNetFastAI': 0.8931572629051621,
  'XGBoost': 0.9043617446978791,
  'NeuralNetTorch': 0.8971588635454182,
  'LightGBMLarge': 0.9115646258503401,
  'WeightedEnsemble_L2': 0.9179671868747499},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestGini': ['RandomForestGini'],
  'RandomForestEntr': ['RandomForestEntr'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesGini': ['ExtraTreesGini'],
  'ExtraTreesEntr': ['ExtraTreesEntr'],
  'NeuralNetFastAI': ['NeuralNetFastAI'],
  'XGBoost': ['XGBoost'],
  'NeuralNetTorch': ['NeuralNetTorch'],
  'LightGBMLarge': ['LightGBMLarge'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'LightGBMXT': 18.154786109924316,
  'LightGBM': 8.476638078689575,
  'RandomForestGini': 3.1614511013031006,
  'RandomForestEntr': 5.085143089294434,
  'CatBoost': 12.856599807739258,
  'ExtraTreesGini': 1.095810890197754,
  'ExtraTreesEntr': 0.8986098766326904,
  'NeuralNetFastAI': 32.44180488586426,
  'XGBoost': 4.243118047714233,
  'NeuralNetTorch': 82.6844220161438,
  'LightGBMLarge': 24.028976917266846,
  'WeightedEnsemble_L2': 0.05867290496826172},
 'model_pred_times': {'LightGBMXT': 0.07304668426513672,
  'LightGBM': 0.13117313385009766,
  'RandomForestGini': 0.12274789810180664,
  'RandomForestEntr': 0.1000359058380127,
  'CatBoost': 0.013782024383544922,
  'ExtraTreesGini': 0.051566123962402344,
  'ExtraTreesEntr': 0.04626035690307617,
  'NeuralNetFastAI': 0.09531092643737793,
  'XGBoost': 0.03696894645690918,
  'NeuralNetTorch': 0.03171801567077637,
  'LightGBMLarge': 0.04468798637390137,
  'WeightedEnsemble_L2': 0.0005331039428710938},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'num_classes': 2,
 'model_hyperparams': {'LightGBMXT': {'learning_rate': 0.05,
   'extra_trees': True,
   'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'RandomForestEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'Accuracy',
   'random_seed': 0},
  'ExtraTreesGini': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'gini',
   'random_state': 0},
  'ExtraTreesEntr': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'entropy',
   'random_state': 0},
  'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'binary:logistic',
   'booster': 'gbtree',
   'seed': 0},
  'NeuralNetTorch': {'num_epochs': 1000,
   'epochs_wo_improve': None,
   'activation': 'relu',
   'embedding_size_factor': 1.0,
   'embed_exponent': 0.56,
   'max_embedding_dim': 100,
   'y_range': None,
   'y_range_extend': 0.05,
   'dropout_prob': 0.1,
   'optimizer': 'adam',
   'learning_rate': 0.0003,
   'weight_decay': 1e-06,
   'proc.embed_min_categories': 4,
   'proc.impute_strategy': 'median',
   'proc.max_category_levels': 100,
   'proc.skew_threshold': 0.99,
   'use_ngram_features': False,
   'num_layers': 4,
   'hidden_size': 128,
   'max_batch_size': 512,
   'use_batchnorm': False,
   'loss_function': 'auto',
   'seed_value': 0},
  'LightGBMLarge': {'learning_rate': 0.03,
   'num_leaves': 128,
   'feature_fraction': 0.9,
   'min_data_in_leaf': 3,
   'seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                   model  score_val eval_metric  pred_time_val   fit_time  \
 0   WeightedEnsemble_L2   0.917967    accuracy       0.319571  33.430055
 1      RandomForestEntr   0.913165    accuracy       0.100036   5.085143
 2      RandomForestGini   0.913165    accuracy       0.122748   3.161451
 3         LightGBMLarge   0.911565    accuracy       0.044688  24.028977
 4        ExtraTreesEntr   0.908764    accuracy       0.046260   0.898610
 5              LightGBM   0.906363    accuracy       0.131173   8.476638
 6        ExtraTreesGini   0.905962    accuracy       0.051566   1.095811
 7               XGBoost   0.904362    accuracy       0.036969   4.243118
 8              CatBoost   0.897559    accuracy       0.013782  12.856600
 9            LightGBMXT   0.897559    accuracy       0.073047  18.154786
 10       NeuralNetTorch   0.897159    accuracy       0.031718  82.684422
 11      NeuralNetFastAI   0.893157    accuracy       0.095311  32.441805

     pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
 0                 0.000533           0.058673            2       True
 1                 0.100036           5.085143            1       True
 2                 0.122748           3.161451            1       True
 3                 0.044688          24.028977            1       True
 4                 0.046260           0.898610            1       True
 5                 0.131173           8.476638            1       True
 6                 0.051566           1.095811            1       True
 7                 0.036969           4.243118            1       True
 8                 0.013782          12.856600            1       True
 9                 0.073047          18.154786            1       True
 10                0.031718          82.684422            1       True
 11                0.095311          32.441805            1       True

     fit_order
 0          12
 1           4
 2           3
 3          11
 4           7
 5           2
 6           6
 7           9
 8           5
 9           1
 10         10
 11          8  }

### Validation

The model above uses Cross Validation on the training set to evaluate model performance. Let's now evaluate the model performance on the unseen test data:

To validate this model, we first drop the label from our test data and subsequently store it:

In [17]:
y_test = test_data["booking_status"]
test_data = test_data.drop(columns=["booking_status"])

Calling **predict(test_data)** uses the best model for inference. Note how the .predict() method would let you predict on a data from a Pandas DataFrame:

In [18]:
y_pred = predictor.predict(test_data)

autogluon comes with a variety of metrics which you can access using **evaluate_predictions()**.
Setting the parameter *auxiliary_metrics=True* computes additional problem specific (automatically determined) metrics depending on whether its classification or regression, we recommend setting this to True to see all the metrics:

In [20]:
metrics = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)
metrics

{'accuracy': 0.900398406374502,
 'balanced_accuracy': np.float64(0.8756499823484614),
 'mcc': 0.7679461999450518,
 'f1': 0.9279870952874755,
 'precision': 0.911911231884058,
 'recall': 0.9446399249354914}

In comparison, *auxiliary_metrics=False*

In [21]:
metrics = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=False)
metrics

{'accuracy': 0.900398406374502}

Autogluon was able to achieve an impressive result, especially given that our dataset is quite imbalanced/

In [22]:
train_data["booking_status"].value_counts()

booking_status
Not_Canceled    20127
Canceled         9873
Name: count, dtype: int64

### Inference on a new datapoint.
Assuming that a customer just booked a room in your hotel, is it likely that the reservation will be cancelled?

In [23]:
reservation = {
    "Booking_ID" : "INN01961234234",
    "no_of_adults" : 1,
    "no_of_children" : 0,
    "no_of_weekend_nights" : 0,
    "no_of_week_nights" : 3,
    "type_of_meal_plan" : "Meal Plan 1",
    "required_car_parking_space" : 0,
    "room_type_reserved" : "Room_Type 1",
    "lead_time" : 190,
    "arrival_year" : 2023,
    "arrival_month" : 11,
    "arrival_date" : 3,
    "market_segment_type" : "Online",
    "repeated_guest" : 0,
    "no_of_previous_cancellations" : 0,
    "no_of_previous_bookings_not_canceled" : 10,
    "avg_price_per_room" : 190.9,
    "no_of_special_requests" : 0
}

To predict on new, unseen data, we need to pass a TabularDataset, a pandas DataFrame or the path to the data

In [25]:
# for a single row dataset, the dictionary needs to be encapsulated in a list
#reservation_data = TabularDataset.from_dict([reservation])
reservation_data = TabularDataset([reservation])

In [27]:
outPUt = predictor.predict(reservation_data)
outPUt

0    Canceled
Name: booking_status, dtype: object

Looks like the customer will cancel its reservation

### Interpretability

An important aspect of machine learning system is to identify the importance of the individual features.
By calling **predictor.feature_importance(train_data)**, we obtain an importance score, paired with std, p_value and the 99th percentile for each feature.<br />
Note, that the label is required for this to work, thus we use train_data

For more information on how the feature importance is calculated check out these two ressource:


https://explained.ai/rf-importance/ <br />
https://scikit-learn.org/stable/modules/permutation_importance.html#id2

In [28]:
predictor.feature_importance(train_data)

These features in provided data are not utilized by the predictor and will be ignored: ['Booking_ID']
Computing feature importance via permutation shuffling for 17 features using 5000 rows with 5 shuffle sets...
	47.52s	= Expected runtime (9.5s per shuffle set)
	11.09s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
lead_time,0.24680,0.003972,8.051274e-09,5,0.254979,0.238621
no_of_special_requests,0.17736,0.008236,5.563255e-07,5,0.194318,0.160402
avg_price_per_room,0.13180,0.006384,6.586133e-07,5,0.144945,0.118655
market_segment_type,0.10808,0.001983,1.359039e-08,5,0.112163,0.103997
arrival_month,0.08088,0.003719,5.350116e-07,5,0.088538,0.073222
arrival_date,0.05300,0.002782,9.077491e-07,5,0.058728,0.047272
no_of_week_nights,0.04224,0.003303,4.448811e-06,5,0.049040,0.035440
no_of_weekend_nights,0.04180,0.002131,8.073925e-07,5,0.046187,0.037413
arrival_year,0.03208,0.001579,7.013568e-07,5,0.035330,0.028830
no_of_adults,0.03032,0.001792,1.458126e-06,5,0.034010,0.026630
type_of_meal_plan,0.02380,0.002059,6.657069e-06,5,0.028040,0.019560
room_type_reserved,0.02188,0.000756,1.710379e-07,5,0.023437,0.020323
required_car_parking_space,0.00556,0.000994,1.175201e-04,5,0.007607,0.003513
no_of_children,0.00544,0.001513,6.489389e-04,5,0.008554,0.002326
repeated_guest,0.00076,0.000573,2.062725e-02,5,0.001939,-0.000419
no_of_previous_bookings_not_canceled,0.00036,0.000261,1.834099e-02,5,0.000897,-0.000177
no_of_previous_cancellations,0.00012,0.000110,3.524200e-02,5,0.000346,-0.000106

It looks like the lead time and the number of special requests are the most important feature for the classifier's decision.
Let's try to augment our previous booking to change the outcome

Let's only change lead_time to 100

In [32]:
reservation = {
    "Booking_ID" : "INN01961234234",
    "no_of_adults" : 1,
    "no_of_children" : 0,
    "no_of_weekend_nights" : 0,
    "no_of_week_nights" : 3,
    "type_of_meal_plan" : "Meal Plan 1",
    "required_car_parking_space" : 0,
    "room_type_reserved" : "Room_Type 1",
    "lead_time" : 100,
    "arrival_year" : 2023,
    "arrival_month" : 11,
    "arrival_date" : 3,
    "market_segment_type" : "Online",
    "repeated_guest" : 0,
    "no_of_previous_cancellations" : 0,
    "no_of_previous_bookings_not_canceled" : 10,
    "avg_price_per_room" : 190.9,
    "no_of_special_requests" : 0
}
## reservation_data = TabularDataset.from_dict([reservation])
reservation_data = TabularDataset([reservation])
predictor.predict(reservation_data)

0    Not_Canceled
Name: booking_status, dtype: object

Awesome - we were able to get a deeper understanding of the decision boundaries of our classifier

In [37]:
# features and Labels
predictor.feature_importance(train_data)

These features in provided data are not utilized by the predictor and will be ignored: ['Booking_ID']
Computing feature importance via permutation shuffling for 17 features using 5000 rows with 5 shuffle sets...
	55.91s	= Expected runtime (11.18s per shuffle set)
	9.94s	= Actual runtime (Completed 5 of 5 shuffle sets)

,importance,stddev,p_value,n,p99_high,p99_low
lead_time,0.24680,0.003972,8.051274e-09,5,0.254979,0.238621
no_of_special_requests,0.17736,0.008236,5.563255e-07,5,0.194318,0.160402
avg_price_per_room,0.13180,0.006384,6.586133e-07,5,0.144945,0.118655
market_segment_type,0.10808,0.001983,1.359039e-08,5,0.112163,0.103997
arrival_month,0.08088,0.003719,5.350116e-07,5,0.088538,0.073222
arrival_date,0.05300,0.002782,9.077491e-07,5,0.058728,0.047272
no_of_week_nights,0.04224,0.003303,4.448811e-06,5,0.049040,0.035440
no_of_weekend_nights,0.04180,0.002131,8.073925e-07,5,0.046187,0.037413
arrival_year,0.03208,0.001579,7.013568e-07,5,0.035330,0.028830
no_of_adults,0.03032,0.001792,1.458126e-06,5,0.034010,0.026630
type_of_meal_plan,0.02380,0.002059,6.657069e-06,5,0.028040,0.019560
room_type_reserved,0.02188,0.000756,1.710379e-07,5,0.023437,0.020323
required_car_parking_space,0.00556,0.000994,1.175201e-04,5,0.007607,0.003513
no_of_children,0.00544,0.001513,6.489389e-04,5,0.008554,0.002326
repeated_guest,0.00076,0.000573,2.062725e-02,5,0.001939,-0.000419
no_of_previous_bookings_not_canceled,0.00036,0.000261,1.834099e-02,5,0.000897,-0.000177
no_of_previous_cancellations,0.00012,0.000110,3.524200e-02,5,0.000346,-0.000106