<a href = "https://www.pieriantraining.com"><img src="../PT Centered Purple.png"> </a>

<em style="text-align:center">Copyrighted by Pierian Training</em>

# Tabular Data: Regression

In this lecture, you are going to build a regression model to predict UBER fares based on features such as

* Pickup Datetime
* Picup Coordinates
* Dropoff Coordinates
* Passenger Count

The dataset is based on : https://www.kaggle.com/datasets/yasserh/uber-fares-dataset

### Imports

In [1]:
from autogluon.tabular import TabularDataset, TabularPredictor

Use **TabularDataset** to load the csv data into a dataframe.

In [3]:
data = TabularDataset("data/uber/uber.csv")

Let's take a look at the data:

In [4]:
data.head()

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 7 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   fare_amount        200000 non-null  float64
 1   pickup_datetime    200000 non-null  object
 2   pickup_longitude   200000 non-null  float64
 3   pickup_latitude    200000 non-null  float64
 4   dropoff_longitude  199999 non-null  float64
 5   dropoff_latitude   199999 non-null  float64
 6   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(1), object(1)
memory usage: 10.7+ MB

In [6]:
len(data)

200000

### Train Test Split

As our dataset is large, we can train on 90% of the data (180k) and validate on the remaining 20k datapoints. Let's use 42 as our random seed again

In [7]:
train_size = 180000
seed = 42

In [8]:
train_data = data.sample(train_size, random_state=seed)
test_data = data.drop(train_data.index)

As previously, we do not need to perform any data preprocessing, AutoGluon is able to recognize the string object as a potential datetime and will perform time feature engineering all on its own!

### Training

We define the save_path and tell the **TabularPredictor** class the desired label - *fare_amount* in our case

In [9]:
save_path = 'uber_predictors'

In [10]:
predictor = TabularPredictor(label="fare_amount", path=save_path)

Let's start the training. Note that it might take some time! 
It should also be noted that autogluon uses the negative root mean squared error as its validation function, thus the minus sign in the metrics reported.

In [11]:
predictor.fit(train_data)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.33 GB / 32.00 GB (19.8%)
Disk Space Avail:   115.14 GB / 926.35 GB (12.4%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (180000 samples, 24.48 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors"
Train Data Rows:    180000
Train Data Columns: 6
Label Column:       fare_amount
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (499.0, -52.0, 11.36729, 9.91752)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6678.04 MB
	Train Data (Original)  Memory Usage: 20.60 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                        : 1 | ['passenger_count']
		('object', ['datetime_as_object']) : 1 | ['pickup_datetime']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                  : 1 | ['passenger_count']
		('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
	4.7s = Fit runtime
	6 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 13.73 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 4.69s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0139, Train Rows: 177498, Val Rows: 2502
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB

[1000]	valid_set's rmse: 5.5302
[2000]	valid_set's rmse: 5.38457
[3000]	valid_set's rmse: 5.32301
[4000]	valid_set's rmse: 5.29179
[5000]	valid_set's rmse: 5.27671
[6000]	valid_set's rmse: 5.27445
[7000]	valid_set's rmse: 5.26169
[8000]	valid_set's rmse: 5.26283
[9000]	valid_set's rmse: 5.26599

	-5.2586	 = Validation score   (-root_mean_squared_error)
	75.02s	 = Training   runtime
	0.17s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.1 GB

[1000]	valid_set's rmse: 5.42633

	-5.3618	 = Validation score   (-root_mean_squared_error)
	16.11s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/6.2 GB

[2000]	valid_set's rmse: 5.37367

	-5.6073	 = Validation score   (-root_mean_squared_error)
	108.56s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=10, gpus=0
	-5.4109	 = Validation score   (-root_mean_squared_error)
	22.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/6.2 GB
	-5.9964	 = Validation score   (-root_mean_squared_error)
	9.7s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=10, gpus=0, mem=0.1/5.8 GB
No improvement since epoch 1: early stopping
	-9.8775	 = Validation score   (-root_mean_squared_error)
	62.88s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=10, gpus=0
	-5.5131	 = Validation score   (-root_mean_squared_error)
	2.83s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.4 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-6.1298	 = Validation score   (-root_mean_squared_error)
	128.1s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB
	-5.4675	 = Validation score   (-root_mean_squared_error)
	16.95s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/6.7 GB
	Ensemble Weights: {'LightGBMXT': 0.739, 'LightGBM': 0.13, 'NeuralNetTorch': 0.13}
	-5.2287	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 448.51s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 11949.6 rows/s (2502 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors")

We can see a summary of the results with: predictor.fit_summary()

In [12]:
predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                 model  score_val              eval_metric  pred_time_val    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0  WeightedEnsemble_L2  -5.228679  root_mean_squared_error       0.209380  219.231543                0.000231           0.006993            2       True         10
1           LightGBMXT  -5.258602  root_mean_squared_error       0.170136   75.020400                0.170136          75.020400            1       True          1
2             LightGBM  -5.361784  root_mean_squared_error       0.023821   16.107809                0.023821          16.107809            1       True          2
3             CatBoost  -5.410911  root_mean_squared_error       0.004675   22.123983                0.004675          22.123983            1       True          4
4        LightGBMLarge  -5.467550  root_mean_squared_error       0.018170   16.949452                0.018170          16.949452            1       True          9
5              XGBoost  -5.513133  root_mean_squared_error       0.005368    2.829551                0.005368           2.829551            1       True          7
6      RandomForestMSE  -5.607309  root_mean_squared_error       0.139750  108.564551                0.139750         108.564551            1       True          3
7        ExtraTreesMSE  -5.996357  root_mean_squared_error       0.074793    9.702514                0.074793           9.702514            1       True          5
8       NeuralNetTorch  -6.129766  root_mean_squared_error       0.015192  128.096340                0.015192         128.096340            1       True          8
9      NeuralNetFastAI  -9.877511  root_mean_squared_error       0.021513   62.881181                0.021513          62.881181            1       True          6
Number of models trained: 10
Types of models trained:
{'TabularNeuralNetTorchModel', 'XGBoostModel', 'XTModel', 'NNFastAiTabularModel', 'LGBModel', 'WeightedEnsembleModel', 'RFModel', 'CatBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
('int', [])                  : 1 | ['passenger_count']
('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
Plot summary of models saved to file: /Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'LightGBMXT': 'LGBModel',
  'LightGBM': 'LGBModel',
  'RandomForestMSE': 'RFModel',
  'CatBoost': 'CatBoostModel',
  'ExtraTreesMSE': 'XTModel',
  'NeuralNetFastAI': 'NNFastAiTabularModel',
  'XGBoost': 'XGBoostModel',
  'NeuralNetTorch': 'TabularNeuralNetTorchModel',
  'LightGBMLarge': 'LGBModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'LightGBMXT': np.float64(-5.25860167746699),
  'LightGBM': np.float64(-5.361784449304389),
  'RandomForestMSE': np.float64(-5.607309050210235),
  'CatBoost': np.float64(-5.4109106211958755),
  'ExtraTreesMSE': np.float64(-5.996357077333316),
  'NeuralNetFastAI': np.float64(-9.877510727211048),
  'XGBoost': np.float64(-5.513132643551914),
  'NeuralNetTorch': np.float64(-6.129765685950299),
  'LightGBMLarge': np.float64(-5.467549744600546),
  'WeightedEnsemble_L2': np.float64(-5.228679272811395)},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'LightGBMXT': ['LightGBMXT'],
  'LightGBM': ['LightGBM'],
  'RandomForestMSE': ['RandomForestMSE'],
  'CatBoost': ['CatBoost'],
  'ExtraTreesMSE': ['ExtraTreesMSE'],
  'NeuralNetFastAI': ['NeuralNetFastAI'],
  'XGBoost': ['XGBoost'],
  'NeuralNetTorch': ['NeuralNetTorch'],
  'LightGBMLarge': ['LightGBMLarge'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'LightGBMXT': 75.02040004730225,
  'LightGBM': 16.10780906677246,
  'RandomForestMSE': 108.56455111503601,
  'CatBoost': 22.123982667922974,
  'ExtraTreesMSE': 9.702513933181763,
  'NeuralNetFastAI': 62.88118100166321,
  'XGBoost': 2.8295512199401855,
  'NeuralNetTorch': 128.09634041786194,
  'LightGBMLarge': 16.94945216178894,
  'WeightedEnsemble_L2': 0.00699305534362793},
 'model_pred_times': {'LightGBMXT': 0.1701359748840332,
  'LightGBM': 0.023821115493774414,
  'RandomForestMSE': 0.13975000381469727,
  'CatBoost': 0.004675149917602539,
  'ExtraTreesMSE': 0.07479310035705566,
  'NeuralNetFastAI': 0.02151322364807129,
  'XGBoost': 0.00536799430847168,
  'NeuralNetTorch': 0.015192031860351562,
  'LightGBMLarge': 0.018169879913330078,
  'WeightedEnsemble_L2': 0.00023102760314941406},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'LightGBMXT': {'learning_rate': 0.05,
   'extra_trees': True,
   'seed': 0},
  'LightGBM': {'learning_rate': 0.05, 'seed': 0},
  'RandomForestMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'CatBoost': {'iterations': 10000,
   'learning_rate': 0.05,
   'allow_writing_files': False,
   'eval_metric': 'RMSE',
   'random_seed': 0},
  'ExtraTreesMSE': {'n_estimators': 300,
   'max_leaf_nodes': 15000,
   'n_jobs': -1,
   'bootstrap': True,
   'criterion': 'squared_error',
   'random_state': 0},
  'NeuralNetFastAI': {'layers': None,
   'emb_drop': 0.1,
   'ps': 0.1,
   'bs': 'auto',
   'lr': 0.01,
   'epochs': 'auto',
   'early.stopping.min_delta': 0.0001,
   'early.stopping.patience': 20,
   'smoothing': 0.0,
   'random_seed': 0},
  'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'reg:squarederror',
   'booster': 'gbtree',
   'seed': 0},
  'NeuralNetTorch': {'num_epochs': 1000,
   'epochs_wo_improve': None,
   'activation': 'relu',
   'embedding_size_factor': 1.0,
   'embed_exponent': 0.56,
   'max_embedding_dim': 100,
   'y_range': None,
   'y_range_extend': 0.05,
   'dropout_prob': 0.1,
   'optimizer': 'adam',
   'learning_rate': 0.0003,
   'weight_decay': 1e-06,
   'proc.embed_min_categories': 4,
   'proc.impute_strategy': 'median',
   'proc.max_category_levels': 100,
   'proc.skew_threshold': 0.99,
   'use_ngram_features': False,
   'num_layers': 4,
   'hidden_size': 128,
   'max_batch_size': 512,
   'use_batchnorm': False,
   'loss_function': 'auto',
   'seed_value': 0},
  'LightGBMLarge': {'learning_rate': 0.03,
   'num_leaves': 128,
   'feature_fraction': 0.9,
   'min_data_in_leaf': 3,
   'seed': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                  model  score_val              eval_metric  pred_time_val  \
 0  WeightedEnsemble_L2  -5.228679  root_mean_squared_error       0.209380
 1           LightGBMXT  -5.258602  root_mean_squared_error       0.170136
 2             LightGBM  -5.361784  root_mean_squared_error       0.023821
 3             CatBoost  -5.410911  root_mean_squared_error       0.004675
 4        LightGBMLarge  -5.467550  root_mean_squared_error       0.018170
 5              XGBoost  -5.513133  root_mean_squared_error       0.005368
 6      RandomForestMSE  -5.607309  root_mean_squared_error       0.139750
 7        ExtraTreesMSE  -5.996357  root_mean_squared_error       0.074793
 8       NeuralNetTorch  -6.129766  root_mean_squared_error       0.015192
 9      NeuralNetFastAI  -9.877511  root_mean_squared_error       0.021513

      fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  219.231543                0.000231           0.006993            2
 1   75.020400                0.170136          75.020400            1
 2   16.107809                0.023821          16.107809            1
 3   22.123983                0.004675          22.123983            1
 4   16.949452                0.018170          16.949452            1
 5    2.829551                0.005368           2.829551            1
 6  108.564551                0.139750         108.564551            1
 7    9.702514                0.074793           9.702514            1
 8  128.096340                0.015192         128.096340            1
 9   62.881181                0.021513          62.881181            1

    can_infer  fit_order
 0       True         10
 1       True          1
 2       True          2
 3       True          4
 4       True          9
 5       True          7
 6       True          3
 7       True          5
 8       True          8
 9       True          6  }

In [13]:
predictor.get_model_best()

AttributeError: 'TabularPredictor' object has no attribute 'get_model_best'

The best result is the **WeightedEnsemble_L2**.
This is, as the name states, not a unique model, but an ensemble consisting of the best models.
During inference, the result is stored for each individual model and then the average is returned as final prediction. You will often see the Weighted Ensemble L2 model as the best model for superbvised learning tasks, which makes sense, as it leverages the best aspects of multiple models.

### Model Loading
To load a model, you can simply call the **load(save_path)** function provided by the TabularPredictor class

In [29]:
save_path = 'uber_predictors'
predictor = TabularPredictor.load(save_path)

### Validation
We again store the test labels separately and drop them from the test dataset before performing inference

In [30]:
y_test = test_data["fare_amount"]
test_data = test_data.drop(columns=["fare_amount"])

In [31]:
y_pred = predictor.predict(test_data)
metrics = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

Evaluation: root_mean_squared_error on test data: -4.516020470232751
	Note: Scores are always higher_is_better. This metric score can be multiplied by -1 to get the metric value.
Evaluations on test data:
{
    "root_mean_squared_error": -4.516020470232751,
    "mean_squared_error": -20.394440887561238,
    "mean_absolute_error": -1.9806206680879594,
    "r2": 0.7858434394747308,
    "pearsonr": 0.8871483667510556,
    "median_absolute_error": -1.1549899578094478
}

 leaderBoard_results = predictor.leaderboard(
        test_data_with_label,
        extra_metrics=["r2", "mean_absolute_error"]
    )

In [18]:
test_data_with_label = test_data.copy()
##test_data_with_label["fare_amount"] = y_test

#leaderBoard_results = predictor.leaderboard(test_data_with_label, extra_info=True)

leaderBoard_results = predictor.leaderboard(test_data, extra_info=True)

In [19]:
display(leaderBoard_results)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
0,RandomForestMSE,-4.413865,-5.607309,root_mean_squared_error,0.319679,0.139750,108.564551,0.319679,0.139750,108.564551,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
1,CatBoost,-4.496030,-5.410911,root_mean_squared_error,0.026381,0.004675,22.123983,0.026381,0.004675,22.123983,...,"{'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'RMSE', 'random_seed': 0}",{'iterations': 2856},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
2,LightGBM,-4.507761,-5.361784,root_mean_squared_error,0.181575,0.023821,16.107809,0.181575,0.023821,16.107809,...,"{'learning_rate': 0.05, 'seed': 0}",{'num_boost_round': 1531},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
3,LightGBMLarge,-4.529406,-5.467550,root_mean_squared_error,0.113390,0.018170,16.949452,0.113390,0.018170,16.949452,...,"{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'seed': 0}",{'num_boost_round': 424},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
4,WeightedEnsemble_L2,-4.553252,-5.228679,root_mean_squared_error,1.526855,0.209380,219.231543,0.001599,0.000231,0.006993,...,"{'use_orig_features': False, 'valid_stacker': True, 'max_base_models': 0, 'max_base_models_per_type': 'auto', 'save_bag_folds': True, 'stratify': 'auto', 'bin': 'auto', 'n_bins': None, 'vary_seed_across_folds': False, 'model_random_seed': 0}",{},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 23},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",[]
5,XGBoost,-4.560500,-5.513133,root_mean_squared_error,0.034758,0.005368,2.829551,0.034758,0.005368,2.829551,...,"{'n_estimators': 10000, 'learning_rate': 0.1, 'n_jobs': -1, 'proc.max_category_levels': 100, 'objective': 'reg:squarederror', 'booster': 'gbtree', 'seed': 0}",{'n_estimators': 528},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
6,LightGBMXT,-4.609760,-5.258602,root_mean_squared_error,1.292922,0.170136,75.020400,1.292922,0.170136,75.020400,...,"{'learning_rate': 0.05, 'extra_trees': True, 'seed': 0}",{'num_boost_round': 7031},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
7,ExtraTreesMSE,-5.296027,-5.996357,root_mean_squared_error,0.262524,0.074793,9.702514,0.262524,0.074793,9.702514,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
8,NeuralNetTorch,-5.791773,-6.129766,root_mean_squared_error,0.050759,0.015192,128.096340,0.050759,0.015192,128.096340,...,"{'num_epochs': 1000, 'epochs_wo_improve': None, 'activation': 'relu', 'embedding_size_factor': 1.0, 'embed_exponent': 0.56, 'max_embedding_dim': 100, 'y_range': None, 'y_range_extend': 0.05, 'dropout_prob': 0.1, 'optimizer': 'adam', 'learning_rate': 0.0003, 'weight_decay': 1e-06, 'proc.embed_min_categories': 4, 'proc.impute_strategy': 'median', 'proc.max_category_levels': 100, 'proc.skew_threshold': 0.99, 'use_ngram_features': False, 'num_layers': 4, 'hidden_size': 128, 'max_batch_size': 512, 'use_batchnorm': False, 'loss_function': 'auto', 'seed_value': 0}","{'batch_size': 256, 'num_epochs': 58}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
9,NeuralNetFastAI,-9.723107,-9.877511,root_mean_squared_error,0.131442,0.021513,62.881181,0.131442,0.021513,62.881181,...,"{'layers': None, 'emb_drop': 0.1, 'ps': 0.1, 'bs': 'auto', 'lr': 0.01, 'epochs': 'auto', 'early.stopping.min_delta': 0.0001, 'early.stopping.patience': 20, 'smoothing': 0.0, 'random_seed': 0}","{'epochs': 30, 'best_epoch': 1}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]

In [20]:
def mostrar_leaderboard_optimizado(leaderboard_df, sort_by='balanced', tolerance_pct=0.05):
        """
        Filtra y ordena el leaderboard de AutoGluon según criterios de producción.

        Parámetros:
        -----------
        leaderboard_df : pd.DataFrame
            El DataFrame devuelto por predictor.leaderboard(...)
        sort_by : str, por defecto 'balanced'
            - 'score': Ordena de mejor a peor precisión.
            - 'speed': Ordena de más rápido a más lento en predecir (pred_time_val).
            - 'balanced': Filtra modelos dentro de la tolerancia de precisión del mejor,
                          y los ordena de más rápidos a más lentos.
        tolerance_pct : float, por defecto 0.05 (5%)
            La pérdida máxima de rendimiento aceptable a cambio de velocidad.
        """
        df = leaderboard_df.copy()

        # Detecta automáticamente si evaluar con test_data (score_test) o validación (score_val)
        score_col = 'score_test' if 'score_test' in df.columns and df['score_test'].notna().any() else 'score_val'

        print(f"🔍 Evaluando con la columna: '{score_col}'")

        if sort_by == 'score':
            df_result = df.sort_values(by=score_col, ascending=False)
            print("🏆 Modelos ordenados por precisión (Score máximo primero):")

        elif sort_by == 'speed':
            df_result = df.sort_values(by='pred_time_val', ascending=True)
            print("⚡ Modelos ordenados por velocidad de predicción (Más rápidos primero):")

        elif sort_by == 'balanced':
            # 1. Encontrar el mejor score
            best_score = df[score_col].max()

            # 2. Calcular el límite inferior aceptable (funciona con métricas positivas y negativas)
            lower_bound = best_score - abs(best_score) * tolerance_pct

            # 3. Filtrar modelos viables
            df_viable = df[df[score_col] >= lower_bound]

            # 4. Ordenar viables por velocidad
            df_result = df_viable.sort_values(by='pred_time_val', ascending=True)

            print(f"⚖️ Enfoque Balanceado para Producción:")
            print(f"   • Mejor score absoluto: {best_score:.4f}")
            print(f"   • Umbral aceptable (tolerancia del {tolerance_pct*100}%): {lower_bound:.4f}")
            print(f"   • Mostrando modelos sobre el umbral, ordenados de más rápidos a más lentos:")

        else:
            raise ValueError("sort_by debe ser 'score', 'speed' o 'balanced'")

        # Mostrar la tabla estilizada en el notebook
        display(df_result)
        return df_result

In [21]:
best_balanced = mostrar_leaderboard_optimizado(
        leaderBoard_results,
        sort_by='balanced',
        tolerance_pct=0.05 # 5% de tolerancia
    )

🔍 Evaluando con la columna: 'score_test'
⚖️ Enfoque Balanceado para Producción:
   • Mejor score absoluto: -4.4139
   • Umbral aceptable (tolerancia del 5.0%): -4.6346
   • Mostrando modelos sobre el umbral, ordenados de más rápidos a más lentos:

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
1,CatBoost,-4.496030,-5.410911,root_mean_squared_error,0.026381,0.004675,22.123983,0.026381,0.004675,22.123983,...,"{'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'RMSE', 'random_seed': 0}",{'iterations': 2856},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
5,XGBoost,-4.560500,-5.513133,root_mean_squared_error,0.034758,0.005368,2.829551,0.034758,0.005368,2.829551,...,"{'n_estimators': 10000, 'learning_rate': 0.1, 'n_jobs': -1, 'proc.max_category_levels': 100, 'objective': 'reg:squarederror', 'booster': 'gbtree', 'seed': 0}",{'n_estimators': 528},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
3,LightGBMLarge,-4.529406,-5.467550,root_mean_squared_error,0.113390,0.018170,16.949452,0.113390,0.018170,16.949452,...,"{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'seed': 0}",{'num_boost_round': 424},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
2,LightGBM,-4.507761,-5.361784,root_mean_squared_error,0.181575,0.023821,16.107809,0.181575,0.023821,16.107809,...,"{'learning_rate': 0.05, 'seed': 0}",{'num_boost_round': 1531},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
0,RandomForestMSE,-4.413865,-5.607309,root_mean_squared_error,0.319679,0.139750,108.564551,0.319679,0.139750,108.564551,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
6,LightGBMXT,-4.609760,-5.258602,root_mean_squared_error,1.292922,0.170136,75.020400,1.292922,0.170136,75.020400,...,"{'learning_rate': 0.05, 'extra_trees': True, 'seed': 0}",{'num_boost_round': 7031},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
4,WeightedEnsemble_L2,-4.553252,-5.228679,root_mean_squared_error,1.526855,0.209380,219.231543,0.001599,0.000231,0.006993,...,"{'use_orig_features': False, 'valid_stacker': True, 'max_base_models': 0, 'max_base_models_per_type': 'auto', 'save_bag_folds': True, 'stratify': 'auto', 'bin': 'auto', 'n_bins': None, 'vary_seed_across_folds': False, 'model_random_seed': 0}",{},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 23},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",[]

In [22]:
best_balanced = mostrar_leaderboard_optimizado(
        leaderBoard_results,
        sort_by='score',
        tolerance_pct=0.05 # 5% de tolerancia
    )

🔍 Evaluando con la columna: 'score_test'
🏆 Modelos ordenados por precisión (Score máximo primero):

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
0,RandomForestMSE,-4.413865,-5.607309,root_mean_squared_error,0.319679,0.139750,108.564551,0.319679,0.139750,108.564551,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
1,CatBoost,-4.496030,-5.410911,root_mean_squared_error,0.026381,0.004675,22.123983,0.026381,0.004675,22.123983,...,"{'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'RMSE', 'random_seed': 0}",{'iterations': 2856},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
2,LightGBM,-4.507761,-5.361784,root_mean_squared_error,0.181575,0.023821,16.107809,0.181575,0.023821,16.107809,...,"{'learning_rate': 0.05, 'seed': 0}",{'num_boost_round': 1531},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
3,LightGBMLarge,-4.529406,-5.467550,root_mean_squared_error,0.113390,0.018170,16.949452,0.113390,0.018170,16.949452,...,"{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'seed': 0}",{'num_boost_round': 424},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
4,WeightedEnsemble_L2,-4.553252,-5.228679,root_mean_squared_error,1.526855,0.209380,219.231543,0.001599,0.000231,0.006993,...,"{'use_orig_features': False, 'valid_stacker': True, 'max_base_models': 0, 'max_base_models_per_type': 'auto', 'save_bag_folds': True, 'stratify': 'auto', 'bin': 'auto', 'n_bins': None, 'vary_seed_across_folds': False, 'model_random_seed': 0}",{},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 23},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",[]
5,XGBoost,-4.560500,-5.513133,root_mean_squared_error,0.034758,0.005368,2.829551,0.034758,0.005368,2.829551,...,"{'n_estimators': 10000, 'learning_rate': 0.1, 'n_jobs': -1, 'proc.max_category_levels': 100, 'objective': 'reg:squarederror', 'booster': 'gbtree', 'seed': 0}",{'n_estimators': 528},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
6,LightGBMXT,-4.609760,-5.258602,root_mean_squared_error,1.292922,0.170136,75.020400,1.292922,0.170136,75.020400,...,"{'learning_rate': 0.05, 'extra_trees': True, 'seed': 0}",{'num_boost_round': 7031},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
7,ExtraTreesMSE,-5.296027,-5.996357,root_mean_squared_error,0.262524,0.074793,9.702514,0.262524,0.074793,9.702514,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
8,NeuralNetTorch,-5.791773,-6.129766,root_mean_squared_error,0.050759,0.015192,128.096340,0.050759,0.015192,128.096340,...,"{'num_epochs': 1000, 'epochs_wo_improve': None, 'activation': 'relu', 'embedding_size_factor': 1.0, 'embed_exponent': 0.56, 'max_embedding_dim': 100, 'y_range': None, 'y_range_extend': 0.05, 'dropout_prob': 0.1, 'optimizer': 'adam', 'learning_rate': 0.0003, 'weight_decay': 1e-06, 'proc.embed_min_categories': 4, 'proc.impute_strategy': 'median', 'proc.max_category_levels': 100, 'proc.skew_threshold': 0.99, 'use_ngram_features': False, 'num_layers': 4, 'hidden_size': 128, 'max_batch_size': 512, 'use_batchnorm': False, 'loss_function': 'auto', 'seed_value': 0}","{'batch_size': 256, 'num_epochs': 58}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
9,NeuralNetFastAI,-9.723107,-9.877511,root_mean_squared_error,0.131442,0.021513,62.881181,0.131442,0.021513,62.881181,...,"{'layers': None, 'emb_drop': 0.1, 'ps': 0.1, 'bs': 'auto', 'lr': 0.01, 'epochs': 'auto', 'early.stopping.min_delta': 0.0001, 'early.stopping.patience': 20, 'smoothing': 0.0, 'random_seed': 0}","{'epochs': 30, 'best_epoch': 1}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]

In [23]:
best_balanced = mostrar_leaderboard_optimizado(
        leaderBoard_results,
        sort_by='speed',
        tolerance_pct=0.05 # 5% de tolerancia
    )

🔍 Evaluando con la columna: 'score_test'
⚡ Modelos ordenados por velocidad de predicción (Más rápidos primero):

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
1,CatBoost,-4.496030,-5.410911,root_mean_squared_error,0.026381,0.004675,22.123983,0.026381,0.004675,22.123983,...,"{'iterations': 10000, 'learning_rate': 0.05, 'allow_writing_files': False, 'eval_metric': 'RMSE', 'random_seed': 0}",{'iterations': 2856},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
5,XGBoost,-4.560500,-5.513133,root_mean_squared_error,0.034758,0.005368,2.829551,0.034758,0.005368,2.829551,...,"{'n_estimators': 10000, 'learning_rate': 0.1, 'n_jobs': -1, 'proc.max_category_levels': 100, 'objective': 'reg:squarederror', 'booster': 'gbtree', 'seed': 0}",{'n_estimators': 528},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
8,NeuralNetTorch,-5.791773,-6.129766,root_mean_squared_error,0.050759,0.015192,128.096340,0.050759,0.015192,128.096340,...,"{'num_epochs': 1000, 'epochs_wo_improve': None, 'activation': 'relu', 'embedding_size_factor': 1.0, 'embed_exponent': 0.56, 'max_embedding_dim': 100, 'y_range': None, 'y_range_extend': 0.05, 'dropout_prob': 0.1, 'optimizer': 'adam', 'learning_rate': 0.0003, 'weight_decay': 1e-06, 'proc.embed_min_categories': 4, 'proc.impute_strategy': 'median', 'proc.max_category_levels': 100, 'proc.skew_threshold': 0.99, 'use_ngram_features': False, 'num_layers': 4, 'hidden_size': 128, 'max_batch_size': 512, 'use_batchnorm': False, 'loss_function': 'auto', 'seed_value': 0}","{'batch_size': 256, 'num_epochs': 58}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
3,LightGBMLarge,-4.529406,-5.467550,root_mean_squared_error,0.113390,0.018170,16.949452,0.113390,0.018170,16.949452,...,"{'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'seed': 0}",{'num_boost_round': 424},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
9,NeuralNetFastAI,-9.723107,-9.877511,root_mean_squared_error,0.131442,0.021513,62.881181,0.131442,0.021513,62.881181,...,"{'layers': None, 'emb_drop': 0.1, 'ps': 0.1, 'bs': 'auto', 'lr': 0.01, 'epochs': 'auto', 'early.stopping.min_delta': 0.0001, 'early.stopping.patience': 20, 'smoothing': 0.0, 'random_seed': 0}","{'epochs': 30, 'best_epoch': 1}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
2,LightGBM,-4.507761,-5.361784,root_mean_squared_error,0.181575,0.023821,16.107809,0.181575,0.023821,16.107809,...,"{'learning_rate': 0.05, 'seed': 0}",{'num_boost_round': 1531},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
7,ExtraTreesMSE,-5.296027,-5.996357,root_mean_squared_error,0.262524,0.074793,9.702514,0.262524,0.074793,9.702514,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
0,RandomForestMSE,-4.413865,-5.607309,root_mean_squared_error,0.319679,0.139750,108.564551,0.319679,0.139750,108.564551,...,"{'n_estimators': 300, 'max_leaf_nodes': 15000, 'n_jobs': -1, 'bootstrap': True, 'criterion': 'squared_error', 'random_state': 0}",{'n_estimators': 300},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]
6,LightGBMXT,-4.609760,-5.258602,root_mean_squared_error,1.292922,0.170136,75.020400,1.292922,0.170136,75.020400,...,"{'learning_rate': 0.05, 'extra_trees': True, 'seed': 0}",{'num_boost_round': 7031},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
4,WeightedEnsemble_L2,-4.553252,-5.228679,root_mean_squared_error,1.526855,0.209380,219.231543,0.001599,0.000231,0.006993,...,"{'use_orig_features': False, 'valid_stacker': True, 'max_base_models': 0, 'max_base_models_per_type': 'auto', 'save_bag_folds': True, 'stratify': 'auto', 'bin': 'auto', 'n_bins': None, 'vary_seed_across_folds': False, 'model_random_seed': 0}",{},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 23},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}","[LightGBM, LightGBMXT, NeuralNetTorch]",[]

### Feature Processing
By using **predictor.transform_features()** we can take a look the the feature engineering autogluon performs.
We can see that it converts *pickup_datetime* into the columns year, month, day and dayofweek.
It automatically recognized that this column contains a timestamp!

In [24]:
predictor.transform_features()

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_datetime,pickup_datetime.year,pickup_datetime.month,pickup_datetime.day,pickup_datetime.dayofweek
181147,-73.973382,40.758758,-73.975726,40.752431,1,1412111412000000000,2014,9,30,1
11872,-73.991657,40.749813,-73.975553,40.754817,2,1285239392000000000,2010,9,23,3
59780,-74.015345,40.715857,-73.984415,40.754312,6,1333468260000000000,2012,4,3,1
134326,-73.968078,40.762517,-73.988275,40.752637,2,1396358100000000000,2014,4,1,1
21277,-73.987672,40.722537,-73.985028,40.678245,2,1247980560000000000,2009,7,19,6
...,...,...,...,...,...,...,...,...,...,...
67094,-74.001332,40.729155,-73.988511,40.737315,1,1355663532000000000,2012,12,16,6
14101,-73.989483,40.720613,-73.990403,40.750275,1,1246581480000000000,2009,7,3,4
66238,-73.998195,40.745543,-73.964765,40.791767,1,1278757980000000000,2010,7,10,5
47096,-73.951360,40.778580,-73.977285,40.751966,1,1240663672000000000,2009,4,25,5
132021,-73.984367,40.764740,-73.987572,40.753059,2,1435650754000000000,2015,6,30,1

In [25]:
predictor.transform_features().columns

Index(['pickup_longitude', 'pickup_latitude', 'dropoff_longitude',
       'dropoff_latitude', 'passenger_count', 'pickup_datetime',
       'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day',
       'pickup_datetime.dayofweek'],
      dtype='object')

### Feature Importance

In [26]:
predictor.feature_importance(train_data)

Computing feature importance via permutation shuffling for 6 features using 5000 rows with 5 shuffle sets...
	21.2s	= Expected runtime (4.24s per shuffle set)
	18.21s	= Actual runtime (Completed 5 of 5 shuffle sets)

                   importance    stddev   p_value  n  p99_high   p99_low
dropoff_latitude     6.150905  0.541699  0.000007  5  7.266270  5.035540
dropoff_longitude    5.917162  0.597541  0.000012  5  7.147507  4.686817
pickup_latitude      4.064624  0.513451  0.000030  5  5.121827  3.007422
pickup_longitude     3.826192  0.490907  0.000032  5  4.836976  2.815407
pickup_datetime      1.387615  0.365153  0.000526  5  2.139469  0.635760
passenger_count      0.081164  0.028554  0.001570  5  0.139956  0.022371

## Inference Constraints

If fast inference is an important criteria, you can pass it to autogluon as a training constraint.
Let's say, that inference speed has to be smaller than 6ms on a single datapoint

If you receive an **Impossible to satisfy inference constraint** error, try increasing the time limit by a small amount

In [27]:
infer_time_limit = 0.0006 # INCREASE IF NECESSARY, ESPECIALLY ON SLOWER COMPUTERS!!
fast_predictor = TabularPredictor(label="fare_amount", path="uber_fast").fit(
    train_data,
    infer_limit=infer_time_limit,
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.36 GB / 32.00 GB (19.9%)
Disk Space Avail:   104.53 GB / 926.35 GB (11.3%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
infer_limit specified, but infer_limit_batch_size was not specified. Setting infer_limit_batch_size=10000
Using hyperparameters preset: hyperparameters='default'
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (180000 samples, 28.71 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_fast"
Train Data Rows:    180000
Train Data Columns: 6
Label Column:       fare_amount
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (499.0, -52.0, 11.36729, 9.91752)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6561.13 MB
	Train Data (Original)  Memory Usage: 20.60 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                        : 1 | ['passenger_count']
		('object', ['datetime_as_object']) : 1 | ['pickup_datetime']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                  : 1 | ['passenger_count']
		('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
	4.8s = Fit runtime
	6 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 13.73 MB (0.2% of available memory)
	0.026ms	= Feature Preprocessing Time (1 row | 10000 batch size)
		Feature Preprocessing requires 4.33% of the overall inference constraint (0.6ms)
		0.574ms inference time budget remaining for models...
Data preprocessing and feature engineering runtime = 5.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0139, Train Rows: 177498, Val Rows: 2502
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.7 GB

[1000]	valid_set's rmse: 5.5302
[2000]	valid_set's rmse: 5.38457
[3000]	valid_set's rmse: 5.32301
[4000]	valid_set's rmse: 5.29179
[5000]	valid_set's rmse: 5.27671
[6000]	valid_set's rmse: 5.27445
[7000]	valid_set's rmse: 5.26169
[8000]	valid_set's rmse: 5.26283
[9000]	valid_set's rmse: 5.26599

	-5.2586	 = Validation score   (-root_mean_squared_error)
	86.68s	 = Training   runtime
	0.17s	 = Validation runtime
	0.065ms	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	0.065ms	 = Validation runtime (1 row | 10000 batch size)
	0.065ms	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	0.065ms	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: LightGBM ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.5 GB

[1000]	valid_set's rmse: 5.42633
[2000]	valid_set's rmse: 5.37367

	-5.3618	 = Validation score   (-root_mean_squared_error)
	15.83s	 = Training   runtime
	0.03s	 = Validation runtime
	8.267μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	8.267μs	 = Validation runtime (1 row | 10000 batch size)
	8.267μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	8.267μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: RandomForestMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/6.7 GB
	-5.6073	 = Validation score   (-root_mean_squared_error)
	111.09s	 = Training   runtime
	0.09s	 = Validation runtime
	0.014ms	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	0.014ms	 = Validation runtime (1 row | 10000 batch size)
	0.014ms	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	0.014ms	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: CatBoost ...
	Fitting with cpus=10, gpus=0
	-5.4109	 = Validation score   (-root_mean_squared_error)
	22.08s	 = Training   runtime
	0.0s	 = Validation runtime
	0.674μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	0.674μs	 = Validation runtime (1 row | 10000 batch size)
	0.674μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	0.674μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/6.5 GB
	-5.9964	 = Validation score   (-root_mean_squared_error)
	9.46s	 = Training   runtime
	0.05s	 = Validation runtime
	0.017ms	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	0.017ms	 = Validation runtime (1 row | 10000 batch size)
	0.017ms	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	0.017ms	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.1 GB
No improvement since epoch 1: early stopping
	-9.8775	 = Validation score   (-root_mean_squared_error)
	60.82s	 = Training   runtime
	0.01s	 = Validation runtime
	4.185μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	4.185μs	 = Validation runtime (1 row | 10000 batch size)
	4.185μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	4.185μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: XGBoost ...
	Fitting with cpus=10, gpus=0
	-5.5131	 = Validation score   (-root_mean_squared_error)
	3.53s	 = Training   runtime
	0.0s	 = Validation runtime
	1.533μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	1.533μs	 = Validation runtime (1 row | 10000 batch size)
	1.533μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	1.533μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.3 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-6.1298	 = Validation score   (-root_mean_squared_error)
	129.26s	 = Training   runtime
	0.01s	 = Validation runtime
	3.458μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	3.458μs	 = Validation runtime (1 row | 10000 batch size)
	3.458μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	3.458μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: LightGBMLarge ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.3 GB
	-5.4675	 = Validation score   (-root_mean_squared_error)
	17.95s	 = Training   runtime
	0.07s	 = Validation runtime
	5.098μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	5.098μs	 = Validation runtime (1 row | 10000 batch size)
	5.098μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	5.098μs	 = Validation runtime (1 row | 10000 batch size | REFIT)
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/6.3 GB
	Ensemble Weights: {'LightGBMXT': 0.739, 'LightGBM': 0.13, 'NeuralNetTorch': 0.13}
	-5.2287	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
	0.048μs	 = Validation runtime (1 row | 10000 batch size | MARGINAL)
	0.076ms	 = Validation runtime (1 row | 10000 batch size)
	0.048μs	 = Validation runtime (1 row | 10000 batch size | REFIT | MARGINAL)
	0.076ms	 = Validation runtime (1 row | 10000 batch size | REFIT)
AutoGluon training complete, total runtime = 463.81s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 12286.9 rows/s (2502 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_fast")

In [28]:
##y_pred = fast_predictor.predict(test_data)
##metrics = fast_predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

NameError: name 'y_test' is not defined

In [30]:
# 1. Extraemos las etiquetas reales y luego las quitamos de los datos de prueba
y_test = test_data["fare_amount"]
test_data = test_data.drop(columns=["fare_amount"])

# 2. Hacemos las predicciones y evaluamos
y_pred = fast_predictor.predict(test_data)
metrics = fast_predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

## Manual hyperparameters

You can of course pass fixed hyperparameters for some (or all models) during training.It should be noted the defaults are usually quite good, and unless you are very familiar with both the data set and the model, you shouldn't expect performance increases based on your own parameter choices.
Let's say you only want to train the neural networks for one epoch and use a learning rate of 1e-2. This should yeild **worse** results (we do this to confirm AutoGluon is using our parameters, in general, its actually sometimes a bit hard to find parameters that would perform **better** than the defaults!).

In [31]:
hyperparams_nn = {"num_epochs": 1, "learning_rate": 1e-2}

We assign the neural network hyperparameters to **NN_TORCH** as we want autogluon to only apply them on the neural network implemented in pytorch.

As you can see in the official documentation, the model name is **NN_TORCH** and not *NeuralNetTorch* as stated above.(https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.fit.html#:~:text=Keys%20are%20strings%20that%20indicate%20which%20model%20types%20to%20train)

"’GBM’ (LightGBM) ‘CAT’ (CatBoost) ‘XGB’ (XGBoost) ‘RF’ (random forest) ‘XT’ (extremely randomized trees) ‘KNN’ (k-nearest neighbors) ‘LR’ (linear regression) ‘NN_TORCH’ (neural network implemented in Pytorch) ‘FASTAI’ (neural network with FastAI backend) ‘AG_AUTOMM’ (MultimodalPredictor from autogluon.multimodal. Supports Tabular, Text, and Image modalities. GPU is required.)"

The reference to all hyperparameters for all models can be found here: 
https://auto.gluon.ai/stable/api/autogluon.tabular.TabularPredictor.fit.html#:~:text=Details%20regarding%20the%20hyperparameters%20you%20can%20specify%20for%20each%20model%20are%20provided%20in%20the%20following%20files%3A

You need to go to the specified file (e.g on github) where you finally can find all hyperparameters
https://github.com/autogluon/autogluon/blob/master/tabular/src/autogluon/tabular/models/tabular_nn/hyperparameters/parameters.py

In [32]:
hyperparameters = {"NN_TORCH": hyperparams_nn}

In [33]:
save_path = 'uber_predictors_manual'

In [34]:
predictor = TabularPredictor(label="fare_amount", path=save_path)

In [35]:
predictor.fit(train_data, hyperparameters=hyperparameters)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.90 GB / 32.00 GB (18.4%)
Disk Space Avail:   100.27 GB / 926.35 GB (10.8%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (180000 samples, 28.71 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual"
Train Data Rows:    180000
Train Data Columns: 6
Label Column:       fare_amount
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (499.0, -52.0, 11.36729, 9.91752)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5921.41 MB
	Train Data (Original)  Memory Usage: 20.60 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                        : 1 | ['passenger_count']
		('object', ['datetime_as_object']) : 1 | ['pickup_datetime']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                  : 1 | ['passenger_count']
		('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
	6.0s = Fit runtime
	6 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 13.73 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 5.99s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0139, Train Rows: 177498, Val Rows: 2502
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{'num_epochs': 1, 'learning_rate': 0.01}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.1/5.8 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-64.592	 = Validation score   (-root_mean_squared_error)
	1.84s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/5.9 GB
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	-64.592	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.95s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 294771.2 rows/s (2502 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual")

We can see two things:
1. The NeuralNetTorch reaches a validation score of -65 which is significantly worse than above. It used our hyperparameters
2. It only uses the models that occur in the hyperparameter dictionary.

To train with more models, we need to specify the model

In [38]:
hyperparameters = {"NN_TORCH": hyperparams_nn, "XGB": {}}

In [39]:
predictor = TabularPredictor(label="fare_amount", path=save_path)

Warning: path already exists! This predictor may overwrite an existing predictor! path="uber_predictors_manual"

In [40]:
predictor.fit(train_data, hyperparameters=hyperparameters)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       6.35 GB / 32.00 GB (19.8%)
Disk Space Avail:   101.05 GB / 926.35 GB (10.9%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (180000 samples, 28.71 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual"
Train Data Rows:    180000
Train Data Columns: 6
Label Column:       fare_amount
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (499.0, -52.0, 11.36729, 9.91752)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    6464.72 MB
	Train Data (Original)  Memory Usage: 20.60 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                        : 1 | ['passenger_count']
		('object', ['datetime_as_object']) : 1 | ['pickup_datetime']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                  : 1 | ['passenger_count']
		('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
	4.7s = Fit runtime
	6 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 13.73 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 4.75s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.0139, Train Rows: 177498, Val Rows: 2502
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{'num_epochs': 1, 'learning_rate': 0.01}],
	'XGB': [{}],
}
Fitting 2 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost ...
	Fitting with cpus=10, gpus=0
	-5.5131	 = Validation score   (-root_mean_squared_error)
	3.38s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.6 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-64.592	 = Validation score   (-root_mean_squared_error)
	1.59s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/6.4 GB
	Ensemble Weights: {'XGBoost': 1.0}
	-5.5131	 = Validation score   (-root_mean_squared_error)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.9s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 311648.8 rows/s (2502 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual")

In [41]:
predictor.fit_summary()

*** Summary of fit() ***
Estimated performance of each model:
                 model  score_val              eval_metric  pred_time_val  fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0              XGBoost  -5.513133  root_mean_squared_error       0.007852  3.377623                0.007852           3.377623            1       True          1
1  WeightedEnsemble_L2  -5.513133  root_mean_squared_error       0.008028  3.381523                0.000176           0.003900            2       True          3
2       NeuralNetTorch -64.592013  root_mean_squared_error       0.007505  1.594246                0.007505           1.594246            1       True          2
Number of models trained: 3
Types of models trained:
{'WeightedEnsembleModel', 'TabularNeuralNetTorchModel', 'XGBoostModel'}
Bagging used: False
Multi-layer stack-ensembling used: False
Feature Metadata (Processed):
(raw dtype, special dtypes):
('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
('int', [])                  : 1 | ['passenger_count']
('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
Plot summary of models saved to file: /Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual/SummaryOfModels.html
*** End of fit() summary ***

{'model_types': {'XGBoost': 'XGBoostModel',
  'NeuralNetTorch': 'TabularNeuralNetTorchModel',
  'WeightedEnsemble_L2': 'WeightedEnsembleModel'},
 'model_performance': {'XGBoost': np.float64(-5.513132643551914),
  'NeuralNetTorch': np.float64(-64.59201332366013),
  'WeightedEnsemble_L2': np.float64(-5.513132643551914)},
 'model_best': 'WeightedEnsemble_L2',
 'model_paths': {'XGBoost': ['XGBoost'],
  'NeuralNetTorch': ['NeuralNetTorch'],
  'WeightedEnsemble_L2': ['WeightedEnsemble_L2']},
 'model_fit_times': {'XGBoost': 3.3776230812072754,
  'NeuralNetTorch': 1.5942459106445312,
  'WeightedEnsemble_L2': 0.003899812698364258},
 'model_pred_times': {'XGBoost': 0.00785207748413086,
  'NeuralNetTorch': 0.007505178451538086,
  'WeightedEnsemble_L2': 0.0001761913299560547},
 'num_bag_folds': 0,
 'max_stack_level': 2,
 'model_hyperparams': {'XGBoost': {'n_estimators': 10000,
   'learning_rate': 0.1,
   'n_jobs': -1,
   'proc.max_category_levels': 100,
   'objective': 'reg:squarederror',
   'booster': 'gbtree',
   'seed': 0},
  'NeuralNetTorch': {'num_epochs': 1,
   'epochs_wo_improve': None,
   'activation': 'relu',
   'embedding_size_factor': 1.0,
   'embed_exponent': 0.56,
   'max_embedding_dim': 100,
   'y_range': None,
   'y_range_extend': 0.05,
   'dropout_prob': 0.1,
   'optimizer': 'adam',
   'learning_rate': 0.01,
   'weight_decay': 1e-06,
   'proc.embed_min_categories': 4,
   'proc.impute_strategy': 'median',
   'proc.max_category_levels': 100,
   'proc.skew_threshold': 0.99,
   'use_ngram_features': False,
   'num_layers': 4,
   'hidden_size': 128,
   'max_batch_size': 512,
   'use_batchnorm': False,
   'loss_function': 'auto',
   'seed_value': 0},
  'WeightedEnsemble_L2': {'use_orig_features': False,
   'valid_stacker': True,
   'max_base_models': 0,
   'max_base_models_per_type': 'auto',
   'save_bag_folds': True,
   'stratify': 'auto',
   'bin': 'auto',
   'n_bins': None,
   'vary_seed_across_folds': False,
   'model_random_seed': 0}},
 'leaderboard':                  model  score_val              eval_metric  pred_time_val  \
 0              XGBoost  -5.513133  root_mean_squared_error       0.007852
 1  WeightedEnsemble_L2  -5.513133  root_mean_squared_error       0.008028
 2       NeuralNetTorch -64.592013  root_mean_squared_error       0.007505

    fit_time  pred_time_val_marginal  fit_time_marginal  stack_level  \
 0  3.377623                0.007852           3.377623            1
 1  3.381523                0.000176           0.003900            2
 2  1.594246                0.007505           1.594246            1

    can_infer  fit_order
 0       True          1
 1       True          3
 2       True          2  }

In [37]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,NeuralNetTorch,-64.592013,root_mean_squared_error,0.008291,1.843124,0.008291,1.843124,1,True,1
1,WeightedEnsemble_L2,-64.592013,root_mean_squared_error,0.008488,1.847373,0.000197,0.004249,2,True,2

In [43]:
test_data_with_label = test_data.copy()
test_data_with_label["fare_amount"] = y_test

# 2. Ejecutamos el leaderboard
predictor.leaderboard(test_data_with_label, extra_info=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,...,hyperparameters,hyperparameters_fit,ag_args_fit,features,compile_time,child_hyperparameters,child_hyperparameters_fit,child_ag_args_fit,ancestors,descendants
0,XGBoost,-4.56050,-5.513133,root_mean_squared_error,0.032427,0.007852,3.377623,0.032427,0.007852,3.377623,...,"{'n_estimators': 10000, 'learning_rate': 0.1, 'n_jobs': -1, 'proc.max_category_levels': 100, 'objective': 'reg:squarederror', 'booster': 'gbtree', 'seed': 0}",{'n_estimators': 528},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[WeightedEnsemble_L2]
1,WeightedEnsemble_L2,-4.56050,-5.513133,root_mean_squared_error,0.033473,0.008028,3.381523,0.001046,0.000176,0.003900,...,"{'use_orig_features': False, 'valid_stacker': True, 'max_base_models': 0, 'max_base_models_per_type': 'auto', 'save_bag_folds': True, 'stratify': 'auto', 'bin': 'auto', 'n_bins': None, 'vary_seed_across_folds': False, 'model_random_seed': 0}",{},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}",[XGBoost],None,"{'ensemble_size': 25, 'subsample_size': 1000000}",{'ensemble_size': 1},"{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': None, 'valid_special_types': None, 'ignored_type_group_special': None, 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None, 'drop_unique': False}",[XGBoost],[]
2,NeuralNetTorch,-64.53201,-64.592013,root_mean_squared_error,0.044633,0.007505,1.594246,0.044633,0.007505,1.594246,...,"{'num_epochs': 1, 'epochs_wo_improve': None, 'activation': 'relu', 'embedding_size_factor': 1.0, 'embed_exponent': 0.56, 'max_embedding_dim': 100, 'y_range': None, 'y_range_extend': 0.05, 'dropout_prob': 0.1, 'optimizer': 'adam', 'learning_rate': 0.01, 'weight_decay': 1e-06, 'proc.embed_min_categories': 4, 'proc.impute_strategy': 'median', 'proc.max_category_levels': 100, 'proc.skew_threshold': 0.99, 'use_ngram_features': False, 'num_layers': 4, 'hidden_size': 128, 'max_batch_size': 512, 'use_batchnorm': False, 'loss_function': 'auto', 'seed_value': 0}","{'batch_size': 256, 'num_epochs': 1}","{'max_memory_usage_ratio': 1.0, 'max_time_limit_ratio': 1.0, 'max_time_limit': None, 'min_time_limit': 0, 'valid_raw_types': ['bool', 'int', 'float', 'category'], 'valid_special_types': None, 'ignored_type_group_special': ['text_ngram', 'text_as_category'], 'ignored_type_group_raw': None, 'get_features_kwargs': None, 'get_features_kwargs_extra': None, 'predict_1_batch_size': None, 'temperature_scalar': None}","[pickup_longitude, pickup_latitude, dropoff_longitude, dropoff_latitude, passenger_count, pickup_datetime, pickup_datetime.year, pickup_datetime.month, pickup_datetime.day, pickup_datetime.dayofweek]",None,None,None,None,[],[]

## Manual validation set during training

If you have strong insights in your dataset it might be helpful to specify some specific validation data to use during training. However, in all other cases, you should rely on autogluon as it uses advanced strategies such as stratified sampling to select the validation data.

Let's define a train-val-test split:

In [48]:
data = TabularDataset("data/uber/uber.csv")

validation_data = data.head(1000)
remaining_data = data.tail(-1000)

Loaded data from: data/uber/uber.csv | Columns = 7 / 7 | Rows = 200000 -> 200000

In [49]:
validation_data

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5
...,...,...,...,...,...,...,...
995,5.7,2011-05-04 06:39:00 UTC,-73.969720,40.757577,-73.953782,40.766960,1
996,8.1,2011-11-23 20:43:20 UTC,-73.993784,40.757054,-73.980018,40.775632,3
997,8.5,2010-01-11 20:58:00 UTC,-73.972338,40.765078,-73.954527,40.783833,5
998,5.5,2013-06-12 17:01:24 UTC,-73.979054,40.784730,-73.982970,40.775048,1
999,9.7,2011-12-11 21:48:22 UTC,-73.983675,40.729944,-73.992416,40.758208,1

In [50]:
remaining_data

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
1000,8.9,2012-06-15 18:02:33 UTC,-73.952845,40.768120,-73.976917,40.779899,1
1001,7.0,2013-11-12 12:41:00 UTC,-73.997807,40.745105,-73.986150,40.734672,1
1002,6.0,2014-12-21 10:53:16 UTC,-73.953874,40.778966,-73.952112,40.791495,1
1003,5.3,2010-03-28 23:21:00 UTC,-73.991827,40.729355,-73.997550,40.741742,1
1004,20.0,2014-03-20 21:41:28 UTC,-74.007019,40.730269,-73.996877,40.694110,1
...,...,...,...,...,...,...,...
199995,3.0,2012-10-28 10:49:00 UTC,-73.987042,40.739367,-73.986525,40.740297,1
199996,7.5,2014-03-14 01:09:00 UTC,-73.984722,40.736837,-74.006672,40.739620,1
199997,30.9,2009-06-29 00:42:00 UTC,-73.986017,40.756487,-73.858957,40.692588,2
199998,14.5,2015-05-20 14:56:25 UTC,-73.997124,40.725452,-73.983215,40.695415,1
199999,14.1,2010-05-15 04:08:00 UTC,-73.984395,40.720077,-73.985508,40.768793,1

In [51]:
train_size = 180000
seed = 42

train_data = remaining_data.sample(train_size, random_state=seed)
test_data = remaining_data.drop(train_data.index)

In [52]:
save_path = 'uber_predictors_manual_val'

In [53]:
predictor = TabularPredictor(label="fare_amount", path=save_path)

We now pass our validation_data to **predictor.fit()** using *tuning_data* argument

In [54]:
predictor.fit(train_data, tuning_data=validation_data)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 25.5.0: Mon Apr 27 20:38:56 PDT 2026; root:xnu-12377.121.6~2/RELEASE_ARM64_T6000
CPU Count:          10
Pytorch Version:    2.9.1
CUDA Version:       CUDA is not available
GPU Count:          WARNING: Exception was raised when calculating GPU count (AssertionError)
Memory Avail:       5.76 GB / 32.00 GB (18.0%)
Disk Space Avail:   100.17 GB / 926.35 GB (10.8%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Using hyperparameters preset: hyperparameters='default'
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (180000 samples, 24.48 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `presets` and `hyperparameters` configuration.
Beginning AutoGluon training ...
AutoGluon will save models to "/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual_val"
Train Data Rows:    180000
Train Data Columns: 6
Tuning Data Rows:    1000
Tuning Data Columns: 6
Label Column:       fare_amount
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (499.0, -52.0, 11.35872, 9.9161)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    5914.85 MB
	Train Data (Original)  Memory Usage: 20.71 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting DatetimeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])                      : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                        : 1 | ['passenger_count']
		('object', ['datetime_as_object']) : 1 | ['pickup_datetime']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])                : 4 | ['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude']
		('int', [])                  : 1 | ['passenger_count']
		('int', ['datetime_as_int']) : 5 | ['pickup_datetime', 'pickup_datetime.year', 'pickup_datetime.month', 'pickup_datetime.day', 'pickup_datetime.dayofweek']
	4.9s = Fit runtime
	6 features in original data used to generate 10 features in processed data.
	Train Data (Processed) Memory Usage: 13.81 MB (0.2% of available memory)
Data preprocessing and feature engineering runtime = 4.93s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 9 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.0 GB

[1000]	valid_set's rmse: 3.9057
[2000]	valid_set's rmse: 3.87218

	-3.8664	 = Validation score   (-root_mean_squared_error)
	28.3s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ...
	Fitting with cpus=10, gpus=0, mem=0.1/5.7 GB

[1000]	valid_set's rmse: 3.86138

	-3.8462	 = Validation score   (-root_mean_squared_error)
	14.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/5.9 GB
	-3.7604	 = Validation score   (-root_mean_squared_error)
	101.05s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	Fitting with cpus=10, gpus=0
	-3.6903	 = Validation score   (-root_mean_squared_error)
	30.9s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesMSE ...
	Fitting with cpus=10, gpus=0, mem=0.8/6.1 GB
	-4.682	 = Validation score   (-root_mean_squared_error)
	9.11s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Fitting with cpus=10, gpus=0, mem=0.1/5.8 GB
	-5.839	 = Validation score   (-root_mean_squared_error)
	91.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	Fitting with cpus=10, gpus=0
	-4.0269	 = Validation score   (-root_mean_squared_error)
	1.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.1 GB
/Users/carlosibarra/projects/autoGluon-Course/.venv/lib/python3.11/site-packages/sklearn/compose/_column_transformer.py:975: FutureWarning: The parameter `force_int_remainder_cols` is deprecated and will be removed in 1.9. It has no effect. Leave it to its default value to avoid this warning.
  warnings.warn(
	-3.6956	 = Validation score   (-root_mean_squared_error)
	348.96s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMLarge ...
	Fitting with cpus=10, gpus=0, mem=0.1/6.3 GB
	-3.9052	 = Validation score   (-root_mean_squared_error)
	13.19s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Fitting 1 model on all data | Fitting with cpus=10, gpus=0, mem=0.0/6.5 GB
	Ensemble Weights: {'CatBoost': 0.389, 'RandomForestMSE': 0.333, 'NeuralNetTorch': 0.278}
	-3.5624	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 645.66s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 17735.1 rows/s (1000 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/Users/carlosibarra/projects/autoGluon-Course/00-Tabular-Data/uber_predictors_manual_val")

### Final evaluation

In [55]:
y_test = test_data["fare_amount"]
test_data = test_data.drop(columns=["fare_amount"])

In [56]:
y_pred = predictor.predict(test_data)

In [57]:
metrics = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)

In [58]:
metrics

{'root_mean_squared_error': np.float64(-4.418243246799805),
 'mean_squared_error': -19.520873387892085,
 'mean_absolute_error': -1.8861215802453692,
 'r2': 0.7967558708721992,
 'pearsonr': 0.8928853184068666,
 'median_absolute_error': -1.0901715755462646}

# Great Job!